### GET request with a header
GET http://localhost:8080
Accept: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = wjj4hjLZgXh0aJJTaqhkY6o-CnAYYbVKkcj063F3IVIYlgMH9QnP4gW8sRpZDKcxD4VQB5sJJxIqVYZn9_nH0hNGFTZ99TQx

### POST request with a header
GET http://localhost:8080/csrfToken
Content-Type: application/json